name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        run: |
          echo "Hello user"


      # Step 3: Install dependencies

      # Step 4: Run tests


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout code again for deployment
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy to server or cloud
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Example: scp files to server or run docker-compose up
